### ISSUE TITLE
错误提示

### ISSUE THREAD

**Issue by xkungfu** [sushang123/php-crontab#1]
[2017-06-22 00:15:25]Waiting for a task
[2017-06-22 00:15:26] Task:[test]->Is Runing Mem:512 kb
PHP Warning:  popen() has been disabled for security reasons in /home/datad/wwwroot/php-crontab-1.0.0/run.php on line 20
PHP Warning:  pclose() expects parameter 1 to be resource, null given in /home/datad/wwwroot/php-crontab-1.0.0/run.php on line 21

**Comment by sushang123** [comment]
popen 这个函数应该是被你的php设置禁用了

**Comment by xkungfu** [comment]
在PHP.ini文件里将disable-functions中的popen删除后，错误提示没有了。
谢谢。
